[versions]
agp = "9.0.0"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
composeBom = "2026.02.00"
lifecycleProcess = "2.10.0"
ktor = "3.4.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.0.1" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.7" }
androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version = "2.11.1" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version = "1.2.0" }

permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version = "0.37.3" }
iptp-proxy = { group = "com.netzarchitekten", name = "IPtProxy", version = "5.1.1" }
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }
material-kolor = { module = "com.materialkolor:material-kolor", version = "4.1.1" }
ktor = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-content-negociation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

[bundles]
kotlin = [
    "junit",
]
androidx = [
    "androidx-core-ktx",
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-lifecycle-runtime-ktx",
    "androidx-activity-compose",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-ui-test-manifest",
    "androidx-compose-ui-test-junit4",
    "androidx-compose-material3",
    "androidx-lifecycle-process",
    "androidx-navigation",
    "androidx-work",
    "androidx-datastore",
]
app = [
    "permissions",
    # "iptp-proxy",
    "timber",
    "material-kolor",
    "ktor",
    "ktor-cio",
    "ktor-content-negociation",
    "ktor-json",
]